# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26032b92075b59052664738dbc944bc4986798c68ba92a471a8dea6922d1acc167d2cc8a71ff96290337e6453834b08fe0439f02c3f480626e44b6f93c191550

test:
  secret_key_base: 7d014ec9f6a7a269b094cf62fb4891e2c81d09b9eaeaaf6215275c64873b830e1888e4091c8992dfc032769db5e1f1e175e9e618aba3106dd685fda49ca22006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
